core/hero_main/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required, current_user

from sqlalchemy.exc import IntegrityError

from core import db
from core.models import Hero, HeroPoints

from core.hero_main.forms import CreateHeroForm, ReviveHeroForm

from core.utils.hero_stuff import acc_has_hero, hp_max, hp_regeneration, revive_hero, battle_return_time
from core.utils.unread_msgs import unread_msgs

from datetime import datetime, timedelta

hero = Blueprint("hero_main", __name__)


@hero.route("/hero/", methods=["POST", "GET"])
@hero.route("/hero/overview", methods=["POST", "GET"])
@login_required
def hero_home():
    """
    Homepage for hero_main
    """

    # Check if the account has a hero_main created
    # If FALSE redirect user to create a hero_main
    if acc_has_hero(current_user.id):
        return redirect(url_for("hero_main.hero_create"))

    # Get the number of unread messages
    get_unread_msgs = unread_msgs(current_user.username)

    # Get the Hero from DB. Needed for overview page to list Hero details
    hero = db.session.query(Hero, HeroPoints).\
        join(HeroPoints, Hero.hid == HeroPoints.hpid).\
        filter(Hero.hid == current_user.id).\
        first()

    # Check if the hero_main is returning from a battle
    if hero[0].action == 1:
        battle_return_time(current_user.id)

    # Get the Max HP of the hero_main based on HP Points
    max_hp = hp_max(hero[1].hp_point)

    # Regenerate HP of hero_main if it is lower then hp_max
    hp_regeneration(current_user.id)

    # Reviving Hero if it is in state of reviving
    if hero[0].alive == 1:
        revive_hero(current_user.id)

    # Revive and Kill Hero Form
    # Kill hero_main is just for testing purposes
    form = ReviveHeroForm()

    if form.h_kill.data and form.validate_on_submit():
        hero[0].hp = 0
        hero[0].alive = 0
        db.session.commit()

    if form.h_revive.data and form.validate_on_submit():
        hero[0].death_check = datetime.now()
        hero[0].alive = 1
        db.session.commit()

    if form.h_upd_points and form.validate_on_submit():
        pass

    # Time when the hero_main is alive again
    reviving_time = hero[0].death_check + timedelta(seconds=hero[0].revive_time)

    # Time when hero_main will arrive from battle
    returning_time = hero[0].return_from_action + timedelta(seconds=hero[0].return_seconds)

    # Calculates the time when HP will be full
    hp_full_time = hero[0].hp_check_regen + timedelta(seconds=max_hp - hero[0].hp)

    return render_template("hero_home.html", hero=hero, form=form, max_hp=max_hp, hp_full_time=hp_full_time,
                           get_unread_msgs=get_unread_msgs, reviving_time=reviving_time, returning_time=returning_time)


@hero.route("/hero/create", methods=["POST", "GET"])
@login_required
def hero_create():
    """
    If you do not have a hero_main, create one here.
    """

    # Check if the account has a hero_main created
    # If TRUE redirect user to Overview Page
    if not acc_has_hero(current_user.id):
        return redirect(url_for("hero_main.hero_home"))

    form = CreateHeroForm()

    # Get the number of unread messages
    get_unread_msgs = unread_msgs(current_user.username)

    if form.validate_on_submit():
        try:
            hero_main = Hero(
                hid=current_user.id,
                name=form.h_name.data,
                gender=form.h_gender.data,
                date_created=datetime.now(),
                level=1,
                current_exp=0,
                next_lvl_exp=100,
                hp=100,
                hp_regen_rate=1,
                hp_check_regen=datetime.now(),
                alive=2,
                death_check=datetime.now(),
                revive_time=10,
                action=0,
                return_from_action=datetime.now(),
                return_seconds=0)

            hero_points = HeroPoints(
                hpid=current_user.id,
                unused_points=0,
                hp_point=5,
                attack_point=5)

            db.session.add(hero_main)
            db.session.add(hero_points)

            db.session.commit()

            flash("Hero created successfully.", "success")
            return redirect(url_for("hero_main.hero_home"))
        except IntegrityError:
            flash("`" + form.h_name.data + "` already exists. Please choose another name for your hero_main.",
                  "warning")
            return redirect(url_for("hero_main.hero_create"))

    return render_template("hero_create.html", form=form, get_unread_msgs=get_unread_msgs)


@hero.route("/hero/delete")
def hero_delete():
    """
    Delete The current hero_main.
    """

    hero_main = Hero.query.filter_by(hid=current_user.id).first()
    hero_attack_pts = HeroPoints.query.filter_by(hpid=current_user.id).first()

    db.session.delete(hero_main)
    db.session.delete(hero_attack_pts)

    db.session.commit()

    flash("Hero has been deleted.", "danger")
    return redirect(url_for("hero_main.hero_home"))

core/hero_train/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, Markup
from flask_login import login_required, current_user

from core import db
from core.models import Hero, HeroPoints, AnimalsTraining
from core.utils.hero_stuff import acc_has_hero, hp_regeneration, hp_max, battle_return_time, level_up, revive_hero
from core.utils.unread_msgs import unread_msgs

from datetime import timedelta, datetime
from random import randint

training = Blueprint("hero_train", __name__)


@training.route("/hero/training")
@login_required
def hero_training():
    """
    Training zone for hero_main
    """

    # Check if the account has a hero_main created
    # If FALSE redirect user to create a hero_main
    if acc_has_hero(current_user.id):
        return redirect(url_for("hero_main.hero_create"))

    # Get the number of unread messages
    get_unread_msgs = unread_msgs(current_user.username)

    # Regenerate HP of hero_main if it is lower then hp_max
    hp_regeneration(current_user.id)

    # Get the Hero from DB. Needed for stats page to list Hero hero_main vital info
    hero = db.session.query(Hero, HeroPoints).\
        join(HeroPoints, Hero.hid == HeroPoints.hpid).\
        filter(Hero.hid == current_user.id).\
        first()

    # Get the Max HP of the hero_main based on HP Points
    max_hp = hp_max(hero[1].hp_point)

    # Calculates the time when HP will be full
    hp_full_time = hero[0].hp_check_regen + timedelta(seconds=max_hp - hero[0].hp)

    # Check if the hero_main is returning from a battle
    if hero[0].action == 1:
        battle_return_time(current_user.id)

    # Check for level Up
    if hero[0].current_exp >= hero[0].next_lvl_exp:
        level_up(current_user.id)

    # Get all animals for the training section
    animals = AnimalsTraining.query.all()

    # Reviving Hero if it is in state of reviving
    if hero[0].alive == 1:
        revive_hero(current_user.id)

    # Time when the hero_main is alive again
    reviving_time = hero[0].death_check + timedelta(seconds=hero[0].revive_time)

    # Time when hero_main will arrive from battle
    returning_time = hero[0].return_from_action + timedelta(seconds=hero[0].return_seconds)

    return render_template("hero_training.html", hero=hero, animals=animals, hp_full_time=hp_full_time,
                           get_unread_msgs=get_unread_msgs, max_hp=max_hp, reviving_time=reviving_time,
                           returning_time=returning_time)


@training.route("/hero/training/lvl_<int:id>")
@login_required
def train(id):
    """
    Training on different levels for different animals
    """

    # Check if the account has a hero_main created
    # If FALSE redirect user to create a hero_main
    if acc_has_hero(current_user.id):
        return redirect(url_for("hero_main.hero_create"))

    # Get the number of unread messages
    get_unread_msgs = unread_msgs(current_user.username)

    # Get the Hero from DB. Needed for stats page to list Hero hero_main vital info
    hero = db.session.query(Hero, HeroPoints).\
        join(HeroPoints, Hero.hid == HeroPoints.hpid).\
        filter(Hero.hid == current_user.id).\
        first()

    # Get the Max HP of the hero_main based on HP Points
    max_hp = hp_max(hero[1].hp_point)

    # if the user enters the link manual, check if the hp is >0 or redirect user home
    if hero[0].hp == 0:
        return redirect(url_for("hero_main.hero_home"))

    # Check for level Up
    if hero[0].current_exp >= hero[0].next_lvl_exp:
        level_up(current_user.id)

    # Check if the hero_main is returning from a battle
    if hero[0].action == 1:
        battle_return_time(current_user.id)

    # Return message if the hero_main is on it's way to somewhere
    if hero[0].action == 1:
        msg = hero[0].name + " is currently returning from a battle. Wait until your hero_main is home and try again!"
        flash(msg, "warning")
        return redirect(url_for("hero_main.hero_home"))

    # Get the animal for the current training level
    animal = AnimalsTraining.query.get_or_404(id)

    # ----- The Process of fighting - 1st try ----- #

    output = []  # output messages

    # Creating variables for the fight
    hero_hp = hero[0].hp
    animal_hp = animal.hp

    while True:
        hero_dmg = randint(round(hero[1].attack_point * 0.5), round(hero[1].attack_point * 1.26))

        animal_hp -= hero_dmg
        if animal_hp <= 0:
            # IF the hero_main wins the battle
            out = hero[0].name + " hit " + animal.name + " with " + str(hero_dmg) + " dmg. " + animal.name + \
                  "  is DEAD. " + hero[0].name + " WON this battle."
            output.append(out)

            # random experience gained from battle based on the value from db
            exp = randint(round(animal.exp_given * 0.76), round(animal.exp_given * 1.26))

            break
        else:
            out = hero[0].name + " hit " + animal.name + " with " + str(hero_dmg) + ". " + animal.name + \
                  " HP is lowered from " + str(animal_hp + hero_dmg) + " to " + str(animal_hp)
            output.append(out)

        animal_dmg = randint(round(animal.attack_point * 0.5), round(animal.attack_point * 1.26))

        hero_hp -= animal_dmg
        if hero_hp <= 0:
            # IF the animal wins the battle
            out = animal.name + " hit " + hero[0].name + " with " + str(animal_dmg) + " dmg. " + hero[0].name + \
                  " is DEAD. " + animal.name + " won this battle."
            output.append(out)

            # if hero_main is dead 0 exp will gain from battle
            exp = 0

            msg_dead = Markup("<i class='far fa-sad-tear'></i> You have died. Revive your hero and try again!")
            flash(msg_dead, "danger")

            break
        else:
            out = animal.name + " hit " + hero[0].name + " with " + str(animal_dmg) + \
                  ". " + hero[0].name + " HP is lowered from " + str(hero_hp + animal_dmg) + " to " + str(hero_hp)
            output.append(out)

    if hero_hp <= 0:
        hero[0].hp = 0
        hero[0].alive = 0
    else:
        hero[0].hp_check_regen = datetime.now()
        hero[0].action = 1
        hero[0].return_from_action = datetime.now()
        hero[0].return_seconds = animal.duration
        hero[0].hp = hero_hp
        hero[0].current_exp += exp

        # Check for level Up
        if hero[0].current_exp >= hero[0].next_lvl_exp:
            level_up(current_user.id)
            msg_lvl_up = "Congratulation, " + hero[0].name + "! You have leveled up!"
            flash(msg_lvl_up, "success")

    db.session.commit()

    # ----- The Battle is Over ----- #

    # Time when hero_main will arrive from battle
    returning_time = hero[0].return_from_action + timedelta(seconds=hero[0].return_seconds)

    # Calculates the time when HP will be full
    hp_full_time = hero[0].hp_check_regen + timedelta(seconds=max_hp - hero[0].hp)

    return render_template("hero_train.html", animal=animal, hero=hero, max_hp=max_hp, hp_full_time=hp_full_time,
                           get_unread_msgs=get_unread_msgs, output=output, exp=exp, returning_time=returning_time)

core/main/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user

from core import db
from core.main.forms import SubscriptionForm
from core.models import Subscription

main = Blueprint("main", __name__)


@main.route("/", methods=["GET", "POST"])
def home():
    if current_user.is_authenticated:
        return redirect(url_for("users.account_home"))

    form = SubscriptionForm()

    if form.validate_on_submit():
        sub = Subscription(email=form.email.data)
        db.session.add(sub)
        db.session.commit()

        flash("Your email has been successfully registered!", "success")

    return render_template("homepage.html", form=form)


@main.route("/about")
def about():
    if current_user.is_authenticated:
        return redirect(url_for("users.account_home"))

    return render_template("about.html")

core/statistics/routes.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

from core import db
from core.models import User, Hero
from core.utils.unread_msgs import unread_msgs

stats = Blueprint("stats", __name__)


@stats.route("/statistics")
@login_required
def statistics():
    stats = db.session.query(User, Hero).\
        outerjoin(Hero, User.id == Hero.hid).\
        order_by(Hero.current_exp.desc(), Hero.level_date.asc(), Hero.name.desc())

    # Get the number of unread messages
    get_unread_msgs = unread_msgs(current_user.username)

    return render_template("statistics.html", stats=stats, get_unread_msgs=get_unread_msgs)

core/users/routes.py
from flask import Blueprint, render_template, flash, request, redirect, url_for
from flask_login import current_user, login_required, login_user, logout_user

from sqlalchemy.exc import IntegrityError

from core import db, bcrypt
from core.models import User
from core.utils.unread_msgs import unread_msgs

from core.users.forms import RegistrationForm, LoginForm, UpdateAccount

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("users.account_home"))

    form = RegistrationForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")

        user = User(
            username=form.username.data,
            email=form.email.data,
            password=hashed_password,
            hidemail=False,
            msg_per_page=5)

        db.session.add(user)
        db.session.commit()

        flash("Your account has been created. You can nou login.", "success")

    return render_template("register.html", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("users.account_home"))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)

            next_page = request.args.get('next')

            return redirect(next_page) if next_page else redirect(url_for("users.account_home"))
        else:
            flash('Login Error. Please check Username and Password', "danger")

    return render_template("login.html", form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.home"))


@users.route("/account")
@login_required
def account_home():

    # Get the number of unread messages
    get_unread_msgs = unread_msgs(current_user.username)
    return render_template("account_home.html", get_unread_msgs=get_unread_msgs)


@users.route("/account/update", methods=["GET", "POST"])
@login_required
def account_update():
    form = UpdateAccount()

    # Get the number of unread messages
    get_unread_msgs = unread_msgs(current_user.username)

    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.hidemail = form.hidemail_checkbox.data
        current_user.msg_per_page = form.msg_per_page.data

        try:
            db.session.commit()
            flash("Your account has been updated.", "success")
            redirect(url_for("users.account_home"))
        except IntegrityError:
            db.session.rollback()

            flash("Username or E-mail already exists.", "danger")
            redirect(url_for("users.account_home"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.hidemail_checkbox.data = current_user.hidemail
        form.msg_per_page.data = current_user.msg_per_page

    return render_template("account_update.html", form=form, get_unread_msgs=get_unread_msgs)


@users.route("/profile/<int:id>")
@login_required
def profile(id):
    user = User.query.get_or_404(id)

    # Get the number of unread messages
    get_unread_msgs = unread_msgs(current_user.username)

    return render_template("profile.html", user=user, get_unread_msgs=get_unread_msgs)

core/templates/account_home.html
{% extends "layout.html" %}

{% block content %}
<section class="account-section">
    <div class="top-slider">
        <div class="container"></div>
    </div>

    <div class="container py-3">
        <div class="row">
            <div class="col-lg">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} text-center">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}

                <h1>Welcome!</h1>
                <p>You are now logged in as <strong>{{ current_user.username }}</strong>!</p>
                <p>View your public profile <a href="{{ url_for('users.profile', id=current_user.id) }}">here</a>.</p>

                {% if get_unread_msgs > 0 %}
                    <p><span class="text-danger">You have {{ get_unread_msgs }} new message{% if get_unread_msgs > 1 %}s{% endif %}.</span>
                        See all unread messages <a href="{{ url_for('msgs.msg_inbox') }}?unread=true">here</a>
                    </p>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

core/templates/hero_create.html
{% extends "hero_layout.html" %}

{% block hero_main %}
<div class="col-lg-10">
    <h4>Create hero</h4>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} text-center">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <form class="form-singin py-5" method="POST">
        {{ form.hidden_tag() }}

        <div class="form-group row">
            {{ form.h_name.label(class="col-sm-2 col-form-label") }}

            {% if form.h_name.errors %}
                <div class="col-sm-4">
                    {{ form.h_name(class="form-control is-invalid") }}
                </div>

                <div class="invalid-feedback">
                    {% for error in form.h_name.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                <div class="col-sm-4">
                    {{ form.h_name(class="form-control") }}
                </div>
            {% endif %}
        </div>

        <div class="form-group row">
            {{ form.h_gender.label(class="col-sm-2 col-form-label") }}

            <div class="col-sm-4">

                {% for i in form.h_gender %}
                    {{ i }}
                    {{ i.label }}
                    <br>
                {% endfor %}
            </div>

        </div>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-dark") }}
        </div>
    </form>
</div>

{% endblock %}

core/templates/hero_training.html
{% extends "hero_layout.html" %}

{% block hero_main %}
<div class="col-lg-8">
    <h4>Training Zone</h4>

    {% if hero[0].alive == 0 %}
    <div class="row pt-5 pb-3">
        <div class="col">
            <h5>Your hero is currently dead.</h5>
        </div>
    </div>
    {% elif hero[0].alive == 1 %}
    <div class="row pt-5 pb-3">
        <div class="col">
            <h5>Your hero is currently reviving. Wait...</h5>
        </div>
    </div>
    {% else %}
    <div class="row pt-5 pb-3">
        <div class="col">
            <h5>Choose your training program:</h5>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="list-group list-group-horizontal pb-5 text-center" id="list-tab" role="tablist">
                {% for animal in animals %}
                <a class="list-group-item list-group-item-action" id="list-home-list" data-toggle="list"
                   href="#animal-{{ animal.name }}" role="tab" aria-controls="home">
                    <strong>{{ animal.name }}</strong><br> Level {{ animal.id }}
                </a>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="tab-content" id="nav-tabContent">
                {% for animal in animals %}
                <div class="tab-pane fade" id="animal-{{ animal.name }}" role="tabpanel" aria-labelledby="list-home-list">
                    <h3>Level {{ animal.id }} - {{ animal.name }}</h3>
                    <p>{{ animal.description }}</p>
                    <hr class="w-25 m-0 py-3">
                    <h5>Animal Stats</h5>

                    <table class="table table-borderless">
                        <tbody>
                            <tr>
                                <td class="col-2">HP</td>
                                <td>{{ animal.hp }}</td>
                            </tr>
                            <tr>
                                <td class="col-2">Damage</td>
                                <td>{{ (animal.attack_point * 0.5)|round|int }}-{{ (animal.attack_point * 1.26)|round|int }}</td>
                            </tr>
                            <tr>
                                <td class="col-2">Experience given</td>
                                <td>{{ (animal.exp_given * 0.76)|round|int }}-{{ (animal.exp_given * 1.26)|round|int }}</td>
                            </tr>
                            <tr>
                                <td class="col-2">Time</td>
                                <td>{{ animal.duration }} seconds</td>
                            </tr>
                        </tbody>
                    </table>
                    <a href="{{ url_for('hero_train.train', id=animal.id) }}" class="btn {% if hero[0].action==0 %}btn-outline-info{% else %}btn-outline-danger disabled{% endif %}">Start Training</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% include "hero_stats.html" %}
{% endblock %}

core/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    {% if title %}
        <title>Death Road - {{ title }}</title>
    {% else %}
        <title>Death Road</title>
    {% endif %}


    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Normalize CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='custom-style.css') }}" rel="stylesheet" type="text/css">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/b2cf7ec02c.js" crossorigin="anonymous"></script>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
</head>

<body id="page-top">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-dark bg-black fixed-top py-3" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="{{ url_for('main.home') }}">Death Road</a>

            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>

            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="heroDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Hero
                            </a>

                            <div class="dropdown-menu" aria-labelledby="heroDropdown">
                                <a class="dropdown-item" href="{{ url_for('hero_main.hero_home') }}">Hero Overview</a>
                                <a class="dropdown-item" href="{{ url_for('hero_train.hero_training') }}">Hero Training</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Messages {% if get_unread_msgs > 0 %}<span class="badge badge-light">{{ get_unread_msgs }}</span>{% endif %}
                            </a>

                            <div class="dropdown-menu" aria-labelledby="messagesDropdown">
                                <a class="dropdown-item" href="{{ url_for('msgs.msg_send') }}">Send Message</a>
                                <a class="dropdown-item" href="{{ url_for('msgs.msg_inbox') }}">Inbox {% if get_unread_msgs > 0 %}<span class="badge badge-dark">{{ get_unread_msgs }}</span>{% endif %}</a>
                                <a class="dropdown-item" href="{{ url_for('msgs.msg_outbox') }}">Outbox</a>
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{{ url_for('stats.statistics') }}">Statistics</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="settingsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Settings
                            </a>

                            <div class="dropdown-menu" aria-labelledby="settingsDropdown">
                                <a class="dropdown-item" href="{{ url_for('users.account_home') }}">Account Home</a>
                                <a class="dropdown-item" href="{{ url_for('users.account_update') }}">Update Account</a>
                                <a class="dropdown-item" href="{{ url_for('users.profile', id=current_user.id) }}">Public Profile</a>
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{{ url_for('users.logout') }}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{{ url_for('main.home') }}#about">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{{ url_for('main.home') }}#story">Story</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{{ url_for('main.home') }}#contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{{ url_for('users.login') }}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{{ url_for('users.register') }}">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}{% endblock %}

    <!-- Footer -->
    <footer class="bg-black small text-center text-white-50">
        <div class="container">
            Copyright &copy; Death Road 2020
        </div>
    </footer>

    <!-- Bootstrap scripts -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Custom scripts for this template -->
    <script src="{{ url_for('static', filename='custom-js.js') }}"></script>
</body>
</html>

core/templates/profile.html
{% extends "layout.html" %}

{% block content %}
<section class="profile-section">
    <div class="top-slider">
        <div class="container"></div>
    </div>

    <div class="container py-3">
        <div class="row">
            <div class="col-lg">
                <h2>Profile</h2>
                <p><strong>Username:</strong> {{ user.username }}</p>
                {% if user.hidemail == 1 %}
                    <p><strong>E-mail:</strong> {{ user.email }}</p>
                {% endif %}

                <p><a href="{{ url_for('msgs.msg_send', to=user.username) }}" class="btn btn-outline-warning">Send Message</a></p>
            </div>
        </div>
    </div>
</section>


{% endblock %}